# .readthedocs.yaml
# Vereist configuratiebestand voor Read the Docs

version: 2

# Specificeer dat we MkDocs gebruiken voor de build
mkdocs:
  configuration: mkdocs.yml

# Definieer de build-omgeving
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      # Installeer de benodigde Python packages uit je requirements.txt
      - pip install -r requirements.txt